const DELIMITER_PATH = "/";
const DELIMITER_URL_PARTS = "?";
const DELIMITER_SEARCH_PARAMS = "&";
const DELIMITER_SEARCH_VALUES = "=";

export { DELIMITER_PATH, DELIMITER_URL_PARTS, DELIMITER_SEARCH_PARAMS, DELIMITER_SEARCH_VALUES };
